.\" Copyright (c) 2016
.\"	Henning Matyschok.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" version=0.2
.\"
.Dd May 26, 2016
.Dt SOD 8
.Os
.Sh NAME
.Nm sod
.Nd Simple sign-on service on demand daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility provides authentication services based on
.Xr pam_unix 8 
module. Messages are passed through blocking
.Ux 
domain streaming socket. 
.Sh FILES
.Bl -tag -width /var/run/sod.pid -compact
.It Pa /var/run/sod.pid
Default process ID file.
.It Pa /var/run/sod.sock
Name of the
.Ux
domain stream socket.
.El
.Sh SEE ALSO
.Xr pam_unix 8 ,
.Xr unix 4 ,
.Xr c_authenticator 3 ,
.Xr c_obj 3 
.Sh HISTORY
The
.Nm
utility appeared, because I need a 
.Xr pam 8
bridge.
.Sh BUGS
There exists no proper options. Only access to authentication services 
based on (local) user database are provided, yet. 
.Pp
Due to the early implementation status of this daemon, 
.Xr c_obj 3 and
.Xr c_authenticator 3 , I've missed to add proper timeout 
values by
.Xr setsockopt 2 
as exception handling on  
.Xr accept 2 ,
.Xr recvmsg 2 
and 
.Xr sendmsg 2 , when those are called for message passing between
.Xr pam_unix 8 
module and 
.Xr sod 8 
daemon.
